# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- script: echo Hello, world!
  displayName: 'Write-Log'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- job: 'Install Pester'
  powershell: Write-Output $PSVErsiontable
  Install-Module -Name Pester -Force -SkipPublisherCheck
  Get-Module -Name Pester
  displayName: 'Install Pester'

- job: 'Run Pester'
  #powershell: Invoke-Pester -OutputFile PesterTest.xml -OutputFormat NUnitXml
  displayName: 'Run Pester'